--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 17.12.2019 17:02:04
-- Server version: 5.5.25
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO shop.videocards(id, name, manufacturer, chipset, frequency, vram, price, img) VALUES
(1, 'NVIDIA GFORCE GTX 1660TI', 'NVIDIA', 'GFORCE GTX 1660TI', 3400, 6, 25000, 'gtx1660ti.png'),
(2, 'NVIDIA GFORCE GTX 2080TI', 'NVIDIA', 'GFORCE GTX 2080TI', 5000, 8, 40000, 'gtx2080ti.png'),
(3, 'AMD Radeon RX 560 PULSE', 'AMD', 'Radeon RX 560 PULSE', 1216, 2, 8000, 'rx560pulse.png'),
(4, 'NVIDIA GeForce GTX 1060 GAMING', 'NVIDIA', 'GeForce GTX 1060 GAMING', 1600, 6, 17000, 'gtx1060gaming.png'),
(5, 'AMD Radeon RX 5700', 'AMD', 'Radeon RX 5700', 1600, 8, 26100, 'rx5700.png');